import { useState } from "react";
import { Pencil } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select } from "@/components/ui/select";
import type { AppSnapshot, FantasyTeam, PsychologyProfile } from "@/types";
import { PROFILE_LABELS } from "@/types";
import { observedBehavior, teamSnapshot } from "@/lib/analytics";

function TeamEditor({ team, data, onSave }: { team: FantasyTeam; data: AppSnapshot; onSave: (t: FantasyTeam) => Promise<void> }) {
  const [draft, setDraft] = useState(team);
  const toggleClub = (club: string) => setDraft((d) => ({ ...d, supportedClubs: d.supportedClubs.includes(club) ? d.supportedClubs.filter((c) => c !== club) : [...d.supportedClubs, club] }));
  return <Dialog><DialogTrigger asChild><Button className="shrink-0" variant="outline" size="sm"><Pencil className="h-3.5 w-3.5" />Modifica</Button></DialogTrigger><DialogContent><DialogTitle className="pr-10 text-xl font-bold">{team.name}</DialogTitle><DialogDescription className="text-sm text-muted-foreground">Psicologia e tifo alimentano il modello di collisione.</DialogDescription><div className="mt-5 space-y-5"><div><div className="mb-2 text-sm font-medium">Psicologia</div><Select className="w-full" value={draft.profile} onChange={(e) => setDraft({ ...draft, profile: e.target.value as PsychologyProfile })}>{Object.entries(PROFILE_LABELS).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</Select></div><div><div className="mb-2 text-sm font-medium">Squadre tifate</div><div className="flex max-h-52 flex-wrap gap-2 overflow-y-auto rounded-lg border p-3">{data.clubs.length ? data.clubs.map((club) => <button key={club.id} className={`min-h-9 rounded-full border px-3 py-1.5 text-xs font-medium ${draft.supportedClubs.includes(club.name) ? "border-primary bg-primary text-primary-foreground" : "hover:bg-accent"}`} onClick={() => toggleClub(club.name)}>{club.name}</button>) : <span className="text-sm text-muted-foreground">Importa i giocatori per avere l'elenco delle squadre.</span>}</div></div><Button className="min-h-11 w-full" onClick={() => void onSave(draft)}>Salva modifiche</Button></div></DialogContent></Dialog>;
}

export function OpponentsPage({ data, onTeam }: { data: AppSnapshot; onTeam: (t: FantasyTeam) => Promise<void> }) {
  return <div className="space-y-4 sm:space-y-6"><div><h1 className="text-2xl font-bold sm:text-3xl">Psicologia avversari</h1><p className="mt-1 text-sm text-muted-foreground sm:text-base">Il profilo iniziale resta modificabile, ma le buste osservate iniziano progressivamente a pesare di più.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.teams.filter((t) => !t.isMe).map((team) => { const snap = teamSnapshot(team, data.players, data.purchases); const behavior = observedBehavior(team, data.players, data.purchases, data.bids); return <Card key={team.id}><CardHeader className="flex-row items-start justify-between gap-3 space-y-0"><div className="min-w-0"><CardTitle className="break-words text-lg sm:text-xl">{team.name}</CardTitle><div className="mt-2 flex flex-wrap gap-1.5"><Badge className="border-primary/30 bg-primary/10 text-primary">{PROFILE_LABELS[team.profile]}</Badge><Badge>{behavior.multiplier.toFixed(2)}× live</Badge></div></div><TeamEditor team={team} data={data} onSave={onTeam} /></CardHeader><CardContent><div className="mb-4 flex flex-wrap gap-1">{team.supportedClubs.length ? team.supportedClubs.map((club) => <Badge key={club}>{club}</Badge>) : <span className="text-xs text-muted-foreground">Nessun tifo impostato</span>}</div><div className="grid grid-cols-3 gap-2 rounded-lg bg-muted p-3 text-center"><div><div className="text-[10px] text-muted-foreground sm:text-xs">Crediti</div><div className="font-bold tabular">{snap.remaining}</div></div><div><div className="text-[10px] text-muted-foreground sm:text-xs">Rosa</div><div className="font-bold tabular">{snap.totalPlayers}/25</div></div><div><div className="text-[10px] text-muted-foreground sm:text-xs">Libero</div><div className="font-bold tabular">{snap.freeBudget}</div></div></div><div className="mt-4"><div className="flex justify-between gap-3 text-[11px] text-muted-foreground sm:text-xs"><span>{behavior.sampleCount} osservazioni</span><span>conf. {Math.round(behavior.confidence * 100)}%</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${behavior.confidence * 100}%` }} /></div><div className="mt-2 text-xs text-muted-foreground">Media offerta: {behavior.averageRatio.toFixed(2)}× quotazione · media lega {behavior.leagueAverage.toFixed(2)}×.</div></div></CardContent></Card> })}</div></div>;
}
